name: finan_tech
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  change_app_package_name: ^1.0.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.1
  flutter_modular: ^3.3.1
  google_sign_in: ^5.0.7
  mobx: ^2.0.3
  shared_preferences: ^2.0.6
  supercharged: ^2.0.0

dev_dependencies:
  build_runner: 2.1.0
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2

flutter_launcher_name:
  name: "KR FinanTech"

flutter:

  uses-material-design: true

  assets:
    - lang/
    - assets/images/

  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
