name: finan_tech
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: any
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  shared_preferences: ^0.5.6+3
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0
  build_runner: 
  effective_dart: ^1.2.1
  
flutter_launcher_name:
  name: "KR FinanTech"

flutter:


  uses-material-design: true

  assets:
   - lang/
   - assets/images/

  fonts:
      - family: Google
        fonts:
          - asset: assets/fonts/ProductSans-Regular.ttf
          - asset: assets/fonts/ProductSans-Bold.ttf
            weight: 700
 